name: better_world
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flame: ^1.10.1
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cloud_firestore: ^4.14.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.6
  fake_cloud_firestore: ^2.4.8
  firebase_core: ^2.24.2
  flame_audio: ^2.1.3
  flutter_svg: ^1.1.6
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  liquid_progress_indicator_v2: ^0.5.0
  logging: ^1.2.0
  lottie: ^3.0.0
  mocktail: ^1.0.3
  nes_ui: ^0.10.0
  overlay_tutorial: ^3.0.0
  package_info_plus: ^5.0.1
  pausable_timer: ^3.1.0+3
  provider: ^6.0.5
  rive: ^0.12.4
  shared_preferences: ^2.2.2
  scratcher: ^2.5.0
  uuid: ^4.3.3
  add_to_google_wallet: ^0.0.3
  smart_snackbars: ^1.0.0

dev_dependencies:
  flame_test: ^1.14.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/challenges/
    - assets/images/challenges/lights_out/
    - assets/images/challenges/ocean_shooter/
    - assets/images/challenges/recycling/
    - assets/images/common/
    - assets/images/dash/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
