name: endless_runner
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flame: ^1.10.1
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  fake_cloud_firestore: ^2.4.8
  firebase_core: ^2.24.2
  flame_audio: ^2.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  lottie: ^3.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  scratcher: ^2.5.0

dev_dependencies:
  flame_test: ^1.14.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/challenges/
    - assets/images/challenges/ocean_shooter/
    - assets/images/dash/
    - assets/images/enemies/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
