// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1jsThMx75Cdk3qyaB_k0fCd8xxLMvU4',
    appId: '1:350421946478:web:6f5b36dbb07fb17ed4567f',
    messagingSenderId: '350421946478',
    projectId: 'flutter-game-challenge',
    authDomain: 'flutter-game-challenge.firebaseapp.com',
    storageBucket: 'flutter-game-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZKp07yUqxFJZMEAZI2OYfd0GzG6tgvb8',
    appId: '1:350421946478:android:3c70c9645bf8d8d9d4567f',
    messagingSenderId: '350421946478',
    projectId: 'flutter-game-challenge',
    storageBucket: 'flutter-game-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARycG4QEWSP02R6dNuNO65qErgOk79u28',
    appId: '1:350421946478:ios:3efe3aeea73a1793d4567f',
    messagingSenderId: '350421946478',
    projectId: 'flutter-game-challenge',
    storageBucket: 'flutter-game-challenge.appspot.com',
    iosBundleId: 'com.example.endlessRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARycG4QEWSP02R6dNuNO65qErgOk79u28',
    appId: '1:350421946478:ios:6df2532bf5ef780cd4567f',
    messagingSenderId: '350421946478',
    projectId: 'flutter-game-challenge',
    storageBucket: 'flutter-game-challenge.appspot.com',
    iosBundleId: 'com.example.endlessRunner.RunnerTests',
  );
}
